// Code generated by gentrait; DO NOT EDIT.
package comp

import "github.com/appcrash/media/server/event"

func (n *RtpSrc) ConfigHandler() {
	n.SetHandler(MtRawByte, n._convertRawByteMessage)
}

func (n *RtpSrc) _convertRawByteMessage(evt *event.Event) {
	if msg, ok := ToMessage[*RawByteMessage](evt); ok {
		n.handleA(msg)
	}
}
