// Code generated by gentrait; DO NOT EDIT.
package comp

import "github.com/appcrash/media/server/event"

// Message Trait Enum
const (
	MrCloneable                    = uint64(1) << 0
	MrChannelable                  = uint64(1) << 1
	MrPreInitializer               = uint64(1) << 2
	MrPostInitializer              = uint64(1) << 3
	MrPreComposer                  = uint64(1) << 4
	MrPostComposer                 = uint64(1) << 5
	UserMessageTraitEnumShiftBegin = 6
)

// Message Type Enum
const (
	MtRawByte = iota
	MtRtpPacket
	MtLinkPoint
	MtConnectNode
	MtChannelLink
	MtUserMessageBegin
)

type RawByteConvertable interface {
	AsRawByteMessage() *RawByteMessage
}

type RtpPacketConvertable interface {
	AsRtpPacketMessage() *RtpPacketMessage
}

type LinkPointConvertable interface {
	AsLinkPointMessage() *LinkPointMessage
}

type ConnectNodeConvertable interface {
	AsConnectNodeMessage() *ConnectNodeMessage
}

type ChannelLinkConvertable interface {
	AsChannelLinkMessage() *ChannelLinkMessage
}

// --------Message Implementation Begin--------
func (m *RawByteMessage) Type() MessageType {
	return MtRawByte
}

func (m *RawByteMessage) AsEvent() *event.Event {
	return event.NewEvent(MtRawByte, m)
}

func (m *RtpPacketMessage) Type() MessageType {
	return MtRtpPacket
}

func (m *RtpPacketMessage) AsEvent() *event.Event {
	return event.NewEvent(MtRtpPacket, m)
}

func (m *LinkPointMessage) Type() MessageType {
	return MtLinkPoint
}

func (m *LinkPointMessage) AsEvent() *event.Event {
	return event.NewEvent(MtLinkPoint, m)
}

func (m *ConnectNodeMessage) Type() MessageType {
	return MtConnectNode
}

func (m *ConnectNodeMessage) AsEvent() *event.Event {
	return event.NewEvent(MtConnectNode, m)
}

func (m *ChannelLinkMessage) Type() MessageType {
	return MtChannelLink
}

func (m *ChannelLinkMessage) AsEvent() *event.Event {
	return event.NewEvent(MtChannelLink, m)
}

// --------Message Implementation End--------

func initMessageTraits() {
	AddMessageTrait(
		MT[RawByteMessage](MetaType[RawByteConvertable]()),
		MT[RtpPacketMessage](MetaType[RtpPacketConvertable]()),
		MT[LinkPointMessage](MetaType[LinkPointConvertable]()),
		MT[ConnectNodeMessage](MetaType[ConnectNodeConvertable]()),
		MT[ChannelLinkMessage](MetaType[ChannelLinkConvertable]()),
	)
}

func initMessageConversion() {
	m := SetMessageConvertable
	m(MtChannelLink, MtRawByte)
}

func init() {
	initMessageTraits()
	initMessageConversion()
}
