package main

import (
	"bufio"
	"html/template"
	"io"
	"os"
)

var (
	msgTempPackage = template.Must(template.New("package").Parse(
		`// Code generated by gentrait; DO NOT EDIT.
package {{ .Name }}
	
`))
	msgTempEnumStart = template.Must(template.New("enum_start").Parse(
		`const (
    {{.Name}} = iota
`))
	msgTempEnumValue = template.Must(template.New("enum").Parse(
		`    {{.Name}}
`))
)

func msgEmitAll() {
	file, err := os.Create(genFile)
	defer func() { file.Close() }()
	if err != nil {
		panic(err)
	}
	writer := bufio.NewWriter(file)
	defer func() { writer.Flush() }()
	msgEmitPackage(writer)
	msgEmitEnum(writer)
}

func msgEmitPackage(w io.Writer) {
	packageName := currentPackageName
	if len(userPackage) == 0 {
		// generate for media project itself
		packageName = "comp"
	}
	msgTempPackage.Execute(w, templateName{packageName})
}

func msgEmitEnum(w io.Writer) {
	var eligible []*messageTypeInfo
	for _, i := range mti {
		if i.isConcrete() {
			eligible = append(eligible, i)
		}
	}
	if len(eligible) == 0 {
		return
	}
	msgTempEnumStart.Execute(w, templateName{eligible[0].enumName()})
	for _, i := range eligible[1:] {
		msgTempEnumValue.Execute(w, templateName{i.enumName()})
	}
	w.Write([]byte(")\n")) // finish const block
}
