package main

import (
	"bufio"
	"io"
	"os"
	"text/template"
)

var (
	msgTempPackage = template.Must(template.New("package").Parse(
		`// Code generated by gentrait; DO NOT EDIT.
package {{ .Name }}

`))
	msgTempImport = template.Must(template.New("import").Parse(`import "{{.Import}}"

`))
	msgTempEnumStart = template.Must(template.New("enum_start").Parse(
		`const (
    {{.Name}} = {{.Start}}
`))
	msgTempEnumValue = template.Must(template.New("enum").Parse(
		`    {{.Name}}
`))
	msgTempConvertableInterface = template.Must(template.New("convertable_interface").Parse(
		`type {{ .InterfaceName }} interface {
    {{ .MethodName }}() *{{ .MessageTypeName }}
}

`))
	msgTempConvertableMappingStart = template.Must(template.New("convertable_mapping_start").Parse(`func initMessageConversion() {
    m := {{.Name}}     
`))
	msgTempConvertableMappingValue = template.Must(template.New("convertable_mapping_value").Parse(
		`    m({{.From}},{{.To}})
`))
	msgTempMessageImpl = template.Must(template.New("message_impl").Parse(
		`func (m *{{.Name}}) Type() {{.MessageType}} {
    return {{.Enum}}
}

func (m *{{.Name}}) AsEvent() *event.Event {
    return event.NewEvent({{.Enum}}, m)
}

`))
	msgTempMetaTypeFuncValue = template.Must(template.New("meta_type_func_value").Parse(
		`        MetaType[{{.Name}}](),
`))
)

func _V(name string) string {
	if isGenForUser() {
		return "comp." + name
	}
	return name
}

var emitMtis []*messageTypeInfo
var emitMriis []*messageTraitInterfaceInfo

func msgEmitAll() {
	if isGenForUser() {
		emitMtis = userMessageTypeInfo
		emitMriis = msgUserTraitInfInfos
	} else {
		emitMtis = concreteMessageTypeInfo
		emitMriis = msgTraitInfInfos
	}
	if len(emitMtis) == 0 {
		panic("no concrete message to generate")
	}

	file, err := os.Create(genFile)
	defer func() { file.Close() }()
	if err != nil {
		panic(err)
	}
	w := bufio.NewWriter(file)
	defer func() { w.Flush() }()

	msgEmitPackage(w)

	msgEmitTraitEnum(w)

	msgEmitEnum(w)
	msgEmitConvertableInterface(w)
	msgEmitMessageImpl(w)

	msgEmitMetaTypeFunc(w)
	msgEmitConvertableMappingFunc(w)
	msgEmitInitFunc(w)

}

func msgEmitPackage(w io.Writer) {
	packageName := currentPackageName
	if !isGenForUser() {
		// generate for media project itself
		packageName = "comp"
	}
	msgTempPackage.Execute(w, templateName{packageName})
	if packageName != "comp" {
		// user package needs import the root package
		msgTempImport.Execute(w, struct{ Import string }{rootPackageName})
	}
	msgTempImport.Execute(w, struct{ Import string }{"github.com/appcrash/media/server/event"})
}

func msgEmitTraitEnum(w *bufio.Writer) {
	if len(emitMriis) == 0 {
		return
	}
	start := "iota"
	if isGenForUser() {
		start = _V(msgTraitEnumEnd)
	}
	w.Write([]byte("// Message Trait Enum\n"))
	msgTempEnumStart.Execute(w, struct{ Name, Start string }{emitMriis[0].enumName(), start})
	for _, i := range emitMriis[1:] {
		msgTempEnumValue.Execute(w, templateName{i.enumName()})
	}
	if !isGenForUser() {
		msgTempEnumValue.Execute(w, templateName{msgTraitEnumEnd})
	}
	w.Write([]byte(")\n\n")) // finish const block
}

func msgEmitEnum(w io.Writer) {
	start := "iota"
	if isGenForUser() {
		start = _V(msgEnumEnd)
	}
	w.Write([]byte("// Message Type Enum\n"))
	msgTempEnumStart.Execute(w, struct{ Name, Start string }{emitMtis[0].enumName(), start})
	for _, i := range emitMtis[1:] {
		msgTempEnumValue.Execute(w, templateName{i.enumName()})
	}
	if !isGenForUser() {
		msgTempEnumValue.Execute(w, templateName{msgEnumEnd})
	}
	w.Write([]byte(")\n\n")) // finish const block
}

func msgEmitMessageImpl(w *bufio.Writer) {
	w.Write([]byte("// --------Message Implementation Begin--------\n"))
	for _, i := range emitMtis {
		msgTempMessageImpl.Execute(w, struct{ Name, Enum, MessageType string }{
			i.typeName(), i.enumName(), _V("MessageType")})
	}
	w.Write([]byte("// --------Message Implementation End--------\n\n"))
}

func msgEmitMetaTypeFunc(w *bufio.Writer) {
	w.Write([]byte(`func initMessageMetaTypes() {
    AddMessageMetaType(
`))
	for _, i := range emitMtis {
		msgTempMetaTypeFuncValue.Execute(w, templateName{i.typeName()})
	}
	w.Write([]byte(")}\n\n")) // finish function block
}

func msgEmitConvertableInterface(w io.Writer) {
	for _, i := range emitMtis {
		msgTempConvertableInterface.Execute(w, struct {
			InterfaceName, MethodName, MessageTypeName string
		}{i.convertInterfaceName(), i.convertMethodName(), i.typeName()})
	}
}

func msgEmitConvertableMappingFunc(w *bufio.Writer) {
	msgTempConvertableMappingStart.Execute(w, templateName{_V("SetMessageConvertable")})
	for _, i := range emitMtis {
		for _, to := range i.convertedTo {
			msgTempConvertableMappingValue.Execute(w, struct{ From, To string }{
				i.enumName(), to.enumName(),
			})
		}
	}
	w.Write([]byte("}\n\n")) // finish function block
}

func msgEmitInitFunc(w *bufio.Writer) {
	w.Write([]byte(`
func init() {
    initMessageMetaTypes()
    initMessageConversion()
}`))
}
