name: Coverity Scan

on:
  schedule:
    - cron: '40 9 * * *'

jobs:
  upload-scan:
    runs-on: ubuntu-latest
    container: appcrash/ffmpeg:debian
    env:
      TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: coverity setup
        run: |
          curl -X POST -d "token=$TOKEN&project=appcrash%2Fmedia" https://scan.coverity.com/download/linux64 -o coverity.tgz 
          mkdir coverity
          tar zxf coverity.tgz --strip 1 -C coverity

      - name: coverity scan
        run: |
          export PATH=`pwd`/coverity/bin:$PATH
          cov-build --dir cov-int make -C codec

      - name: upload data
        run: |
          tar czvf media.tgz cov-int
          curl --form token=$TOKEN --form email=cosmosgleam@gmail.com --form file=@media.tgz --form version="${GITHUB_SHA::10}" --form description="scheduled_scan" https://scan.coverity.com/builds?project=appcrash%2Fmedia




