name: Golang CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.24.2'

      - name: Dependency
        run: |
          apt-get update -qq && \
          apt-get install -y --no-install-recommends \
          ca-certificates \
          build-essential \
          ffmpeg \
          libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev libavcodec-extra \
          libx264-dev libx265-dev libfdk-aac-dev

      - name: Test
        run: CGO_ENABLED=1 go test -v -race -coverprofile=coverage.txt -covermode=atomic ./codec ./server/event ./server/comp/...

      - uses: codecov/codecov-action@v1.5.2
        with:
          files: ./coverage.txt
          verbose: true

