name: Golang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    container: appcrash/ffmpeg:centos7
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.6'

      - name: Test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./codec ./server/event ./server/comp/...

      - uses: codecov/codecov-action@v1.5.2
        with:
          files: ./coverage.txt
          verbose: true

